---
  n_estimators: 
    - 50
    - 100
    - 500
  criterion:
    - "squared_error"
    - "poisson"
  min_samples_split:
    - 0.01
    - 0.1
    - 2
  min_samples_leaf:
    - 1
    - 5
    - 0.1
  max_features:
    - "sqrt"
    - "log2"
    - "auto"
  max_leaf_nodes:
    - 10
    - 100
    - 250
  random_state:
    - 12